/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fyp_turing.model.ui;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author ayekaungmyaphyu
 */
public class Admin_Home extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    
    public Admin_Home() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        user_logout = new javax.swing.JLabel();
        daily_report = new javax.swing.JLabel();
        create_item = new javax.swing.JLabel();
        view_items = new javax.swing.JLabel();
        monthly_report = new javax.swing.JLabel();
        create_category = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(110, 33, 66));
        jPanel7.setForeground(new java.awt.Color(110, 33, 66));

        jPanel8.setBackground(new java.awt.Color(97, 35, 78));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        user_logout.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        user_logout.setForeground(new java.awt.Color(255, 255, 255));
        user_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_logout.setText("LogOut");
        user_logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        user_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(user_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        daily_report.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        daily_report.setForeground(new java.awt.Color(255, 255, 255));
        daily_report.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daily_report.setText("Daily Report");
        daily_report.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        daily_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daily_reportMouseClicked(evt);
            }
        });

        create_item.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        create_item.setForeground(new java.awt.Color(255, 255, 255));
        create_item.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_item.setText("Create New Item");
        create_item.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_itemMouseClicked(evt);
            }
        });

        view_items.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        view_items.setForeground(new java.awt.Color(255, 255, 255));
        view_items.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        view_items.setText("View Listed Items");
        view_items.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_itemsMouseClicked(evt);
            }
        });

        monthly_report.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        monthly_report.setForeground(new java.awt.Color(255, 255, 255));
        monthly_report.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthly_report.setText("Monthly Report");
        monthly_report.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monthly_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthly_reportMouseClicked(evt);
            }
        });

        create_category.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        create_category.setForeground(new java.awt.Color(255, 255, 255));
        create_category.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_category.setText("Create Category");
        create_category.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_categoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(create_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(daily_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_items, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthly_report, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(create_category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(127, 127, 127))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(create_item, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(create_category, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daily_report, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthly_report, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(view_items, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_logoutMouseClicked
        // TODO add your handling code here:
        Login_Form lf = new Login_Form();
            lf.setVisible(true);
            lf.pack();
            lf.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_user_logoutMouseClicked

    private void daily_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daily_reportMouseClicked
        // TODO add your handling code here:
        Daily_Report dr = new Daily_Report();
        dr.setVisible(true);
        dr.pack();
        dr.pack();
        dr.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_daily_reportMouseClicked

    private void create_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_itemMouseClicked
        // TODO add your handling code here:
        Item_Register_Form If = new Item_Register_Form();
        If.setVisible(true);
        If.pack();
        If.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_create_itemMouseClicked

    private void view_itemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_itemsMouseClicked
        // TODO add your handling code here:
        View_Item_Table vt = new View_Item_Table();
        vt.setVisible(true);
        vt.pack();
        vt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_view_itemsMouseClicked

    private void monthly_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthly_reportMouseClicked
        // TODO add your handling code here:
        Monthly_Report mr = new Monthly_Report();
        mr.setVisible(true);
        mr.pack();
        mr.pack();
        mr.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_monthly_reportMouseClicked

    private void create_categoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_categoryMouseClicked
        // TODO add your handling code here:
        Category_Form cf = new Category_Form();
        cf.setVisible(true);
        cf.pack();
        cf.pack();
        cf.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_create_categoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel create_category;
    private javax.swing.JLabel create_item;
    private javax.swing.JLabel daily_report;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JLabel monthly_report;
    private javax.swing.JLabel user_logout;
    private javax.swing.JLabel view_items;
    // End of variables declaration//GEN-END:variables
}
