/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fyp_turing.model.ui;

import fyp_turing.model.Category;
import fyp_turing.model.Item;
import fyp_turing.model.dao.DAOConnection;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayekaungmyaphyu
 */
public class View_Item_Table extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
//    String imagePath = null;
    
    Item item = new Item();
    String imagePath = "";
    boolean isClicked = false;
    String category;
    public View_Item_Table() {
        initComponents();
        
        ArrayList<Category> cat = (ArrayList<Category>) DAOConnection.getDao().getCategory();
         jComboBox_cat.addItem("All");
        for(int i=0;i<cat.size();i++){
            jComboBox_cat.addItem(cat.get(i).getName());
        }
         category = jComboBox_cat.getSelectedItem().toString();
        populateItems(category);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_item = new javax.swing.JTable();
        jButton_edit = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jComboBox_cat = new javax.swing.JComboBox<>();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(110, 33, 66));
        jPanel1.setForeground(new java.awt.Color(110, 33, 66));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registered Items");

        jTable_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Item Name", "Description", "Stock", "Image", "Price", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Byte.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_itemMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_item);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 205, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 143, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jComboBox_cat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_catMouseClicked(evt);
            }
        });
        jComboBox_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_catActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(222, 222, 222))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jComboBox_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jComboBox_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void populateItems(String category){
        DefaultTableModel model = (DefaultTableModel) jTable_item.getModel();
        model.setRowCount(0);
        ArrayList<Item> item = (ArrayList<Item>) DAOConnection.getDao().getItem(category);
        Object rowData[] = new Object[7];
        for(int i = 0; i<item.size();i++){
            rowData[0] = item.get(i).getId();
            rowData[1] = item.get(i).getName();
            rowData[2] = item.get(i).getDescription();
            rowData[3] = item.get(i).getStock();
            if(item.get(i).getImagePath()!=null){
                ImageIcon image = new ImageIcon(new ImageIcon(item.get(i).getImagePath()).getImage().getScaledInstance(150, 120, java.awt.Image.SCALE_SMOOTH));
//            rowData[4] = ResizeImage(null,item.get(i).getImagePath());
                rowData[4] = image;
            }else{
                rowData[4] = null;
            }
            
            rowData[5] = item.get(i).getPrice();
            rowData[6] = item.get(i).getCategory();
            model.addRow(rowData);
        }
    }
    private void jTable_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_itemMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_item.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_item.getModel();
        Long itemId = Long.valueOf(model.getValueAt(selectedRow, 0).toString());
        String itemName = model.getValueAt(selectedRow, 1).toString();
        String itemDescription = model.getValueAt(selectedRow,2).toString();
        Integer itemStock = Integer.valueOf(model.getValueAt(selectedRow,3).toString());
        imagePath = model.getValueAt(selectedRow, 4).toString();
        Float price = Float.valueOf(model.getValueAt(selectedRow,5).toString());
        String category = model.getValueAt(selectedRow,6).toString();
        item = new Item(itemId,itemName,itemDescription,price,itemStock,category);
        isClicked = true;
    }//GEN-LAST:event_jTable_itemMouseClicked

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
        if(item != null){

            Item_Edit_Form rf = new Item_Edit_Form(item,imagePath);
            rf.setVisible(true);
            rf.pack();
            rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            System.out.println(item);
        }else{
            JOptionPane.showMessageDialog(null, "Please select item on table");
        }
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        if(item != null){
            DAOConnection.getDao().deleteItem(item.getName());
            int index = jTable_item.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_item.getModel();
        model.removeRow(index);
//        itemName = null;
        }else{
            JOptionPane.showMessageDialog(null, "Please select item on table");
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jComboBox_catMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_catMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_catMouseClicked

    private void jComboBox_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_catActionPerformed
        // TODO add your handling code here:
        category = jComboBox_cat.getSelectedItem().toString();
        populateItems(category);
    }//GEN-LAST:event_jComboBox_catActionPerformed
    
       //Resize Image
    public ImageIcon ResizeImage(String imagePath, byte[] pic){
        ImageIcon myImage = null;
        if(imagePath != null){
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Item_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JComboBox<String> jComboBox_cat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_item;
    // End of variables declaration//GEN-END:variables
}
