/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fyp_turing.model.ui;

import fyp_turing.model.Category;
import fyp_turing.model.Item;
import fyp_turing.model.Voucher;
import fyp_turing.model.dao.DAOConnection;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayekaungmyaphyu
 */
public class Voucher_Form extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    Voucher voucher = new Voucher();
    Item item = new Item();
    Integer input;
    Integer stock;
    String itemName = "";
    String cancelItem = "";
    Integer cancelQuantity;
    Float itemPrice;
    boolean isClicked = false;
    String cat;
    SimpleDateFormat txtDate = new SimpleDateFormat("dd/MM/yyyy");
    Date date = new Date();
    String todayDate = String.valueOf(txtDate.format(date));
    ArrayList<Voucher> voucherList = new ArrayList<Voucher>();

    public Voucher_Form() {
        initComponents();
        
        jPanel2.setBackground(new Color(0,0,0,40));
        
        jLabel_date.setText(todayDate);
         ArrayList<Category> cat = (ArrayList<Category>) DAOConnection.getDao().getCategory();
         jComboBox_cat.addItem("All");
        for(int i=0;i<cat.size();i++){
            jComboBox_cat.addItem(cat.get(i).getName());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_item = new javax.swing.JTable();
        jButton_insertItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_total = new javax.swing.JLabel();
        jLabel_date = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_selectedItems = new javax.swing.JTable();
        jButton_create = new javax.swing.JButton();
        jComboBox_cat = new javax.swing.JComboBox<>();
        jButton_cancelItem = new javax.swing.JButton();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(110, 33, 66));
        jPanel1.setForeground(new java.awt.Color(110, 33, 66));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Voucher");

        jTable_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Price", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_item.setRowHeight(25);
        jTable_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_itemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_item);

        jButton_insertItem.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton_insertItem.setText(">>");
        jButton_insertItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertItemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel6.setText("Total:         $");

        jLabel_total.setFont(new java.awt.Font("Tamil MN", 0, 18)); // NOI18N
        jLabel_total.setText("--");

        jLabel_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_date.setText("01/01/2019");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Date:");

        jTable_selectedItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Quantity x Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_selectedItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_selectedItemsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable_selectedItems);

        jButton_create.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton_create.setText("Create");
        jButton_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_date, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jButton_create, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_create, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_total))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(463, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jComboBox_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_catActionPerformed(evt);
            }
        });

        jButton_cancelItem.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton_cancelItem.setText("<<");
        jButton_cancelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jComboBox_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_insertItem)
                            .addComponent(jButton_cancelItem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jButton_insertItem)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_cancelItem))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jComboBox_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_insertItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertItemActionPerformed
        // TODO add your handling code here:
        if(isClicked){
            input = Integer.parseInt(JOptionPane.showInputDialog("Please enter quantity: "));
            if(input > 0 && stock>= input){
                
                populateSelectItems();
                
            }else{
                System.out.println("Enter qauntity: ");
            }
            isClicked = false;
        }else{
            JOptionPane.showMessageDialog(null, "Please select item first.");
        }
    }//GEN-LAST:event_jButton_insertItemActionPerformed

    private void jTable_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_itemMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_item.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_item.getModel();
        itemName = model.getValueAt(selectedRow, 0).toString();
        itemPrice = Float.parseFloat(model.getValueAt(selectedRow,2).toString());
        stock = Integer.parseInt(model.getValueAt(selectedRow,3).toString());
        isClicked = true;
        
        
    }//GEN-LAST:event_jTable_itemMouseClicked

    private void jTable_selectedItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_selectedItemsMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_selectedItems.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_selectedItems.getModel();
        cancelItem = model.getValueAt(selectedRow, 0).toString();
       cancelQuantity = Integer.parseInt(model.getValueAt(selectedRow, 2).toString());
       isClicked = true;
    }//GEN-LAST:event_jTable_selectedItemsMouseClicked

    private void jButton_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable_selectedItems.getModel();
        for(int i=0;i<jTable_selectedItems.getRowCount();i++){
            String itemName = model.getValueAt(i, 0).toString();
            Float price = Float.parseFloat(model.getValueAt(i, 1).toString());
            Integer quantity = Integer.parseInt(model.getValueAt(i, 2).toString());
            Float totalCost = price * quantity;
         
            Voucher voucher = new Voucher(todayDate, itemName,price,quantity, totalCost);
            DAOConnection.getDao().insertVoucher(voucher);
        }
      model.setRowCount(0);
        
    }//GEN-LAST:event_jButton_createActionPerformed

    private void jComboBox_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_catActionPerformed
        // TODO add your handling code here:
        cat = jComboBox_cat.getSelectedItem().toString();
        populateItems(cat);
    }//GEN-LAST:event_jComboBox_catActionPerformed

    private void jButton_cancelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelItemActionPerformed
        // TODO add your handling code here:
        if(isClicked){
            Integer Orginalstock= DAOConnection.getDao().getItemStock(cancelItem);
            DAOConnection.getDao().updateQuantity(Orginalstock, cancelQuantity, cancelItem,true);
        populateItems(cat);
        DefaultTableModel model = (DefaultTableModel) jTable_selectedItems.getModel();
        isClicked = false;
        try{
            int SelectedRowIndex = jTable_selectedItems.getSelectedRow();
            model.removeRow(SelectedRowIndex);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Please select item first.");
        }
        
    }//GEN-LAST:event_jButton_cancelItemActionPerformed
    public void populateItems(String category){
       
        
        DefaultTableModel model = (DefaultTableModel) jTable_item.getModel();
           model.setRowCount(0);
         ArrayList<Item> item = (ArrayList<Item>) DAOConnection.getDao().getItem(category);

        Object rowData[] = new Object[4];
        for(int i = 0; i<item.size();i++){
            rowData[0] = item.get(i).getName();
            rowData[1] = item.get(i).getDescription();
            rowData[2] = item.get(i).getPrice();
            rowData[3] = item.get(i).getStock();
            model.addRow(rowData);
        }
        
        
    }
    public void populateSelectItems(){
        DefaultTableModel model = (DefaultTableModel) jTable_selectedItems.getModel();
        Object rowData[] = new Object[4];
            
            rowData[0] = itemName;
            rowData[1] = itemPrice;
            rowData[2] = input;
            rowData[3] = itemPrice * input;
            model.addRow(rowData);

        if(stock >= input){
            DAOConnection.getDao().updateQuantity(stock, input, itemName,false);
        }else{
            JOptionPane.showMessageDialog(null, "Not enough stock");
        }
        populateItems(cat);
//        total += itemPrice * input;
//       jLabel_total.setText(total.toString());
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voucher_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancelItem;
    private javax.swing.JButton jButton_create;
    private javax.swing.JButton jButton_insertItem;
    private javax.swing.JComboBox<String> jComboBox_cat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_date;
    private javax.swing.JLabel jLabel_total;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_item;
    private javax.swing.JTable jTable_selectedItems;
    // End of variables declaration//GEN-END:variables
}
